I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 6, in script call
    call startChapter5
  File "game/chapter5.rpy", line 21, in script
    show aperturova normal at left
Exception: Image 'aperturova' does not accept attributes 'normal'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 6, in script call
    call startChapter5
  File "game/chapter5.rpy", line 21, in script
    show aperturova normal at left
  File "/Users/sema/Desktop/renpy-8.1.3-sdk/renpy/ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "/Users/sema/Desktop/renpy-8.1.3-sdk/renpy/ast.py", line 1391, in show_imspec
    renpy.config.show(name,
  File "/Users/sema/Desktop/renpy-8.1.3-sdk/renpy/exports.py", line 733, in show
    if not base.find_target() and renpy.config.missing_show:
  File "/Users/sema/Desktop/renpy-8.1.3-sdk/renpy/display/image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "/Users/sema/Desktop/renpy-8.1.3-sdk/renpy/display/core.py", line 499, in _duplicate
    args.extraneous()
  File "/Users/sema/Desktop/renpy-8.1.3-sdk/renpy/display/core.py", line 362, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'aperturova' does not accept attributes 'normal'.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.1.3.23091805
Novella 1.0
Fri Dec  1 10:10:29 2023
